### PR TITLE
Require telemetry ~> 1.0

### PR DESCRIPTION
**Pull request by josevalim**

### CODE REVIEW

**Comment by josevalim** [comment]
If all passes, can you please do a new release? I think we will need to bump to 0.4. :)

**Comment by josevalim** [comment]
@binaryseed alternatively, if you give me owner permission on Hex.pm I will be glad to do a new release myself. :)

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by binaryseed** [comment]
Added you as an owner on hex! Changed the version in https://github.com/beam-telemetry/cowboy_telemetry/commit/496fcc5bf021a3135928138eb61826771d739a39

**Pull request merged**
